### PR TITLE
:wrench: Sitemap #24

### PR DESCRIPTION
**Pull request by muriithi-ian**
# Description

Added a sitemap to aid with site navigation and helping the google crawlers understand our website and it's contents

To achieve this, we needed to:

```
- Create a robots text file to allow crawlers
- Create a sitemap to be uploaded with site on deployment
```

Fixes [#24](https://github.com/italanta/elewa-group/issues/24)

## colaborators
@Dcolonel6
@muriithi-ian

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

## Sitemap
image

## robots test file
image

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by muriithi-ian** [comment]
@IanOdhiambo9  Kindly review

**Comment by IanOdhiambo9** [comment]
We'll put the sitemap issue on hold for some of the page developments to complete first.

**Comment by muriithi-ian** [comment]
Can I propose a merge then as we develop we can update the sitemap? Only it's contents will be changing

**Comment by muriithi-ian** [comment]
Can I propose a merge then as we develop we can update the sitemap? Only it's contents will be changing @IanOdhiambo9

**Comment by LemmyMwaura** [comment]
@muriithi-ian. This will be reopened when page developments are completed. Don't worry

**Pull request closed without merging**
