### PR TITLE
Venture labs info

### LINKED ISSUE #402: 🎨 Create venture labs info section
#  Create venture labs info section
---

#### Note: this issue is dependent on #400, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want an info section for the venture-labs page

### Description

The info section contains a number of paragraphs with some info text

The section needs to appear as shown below (link to icons below)

Screenshot 2023-03-06 at 09 02 48

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/61b7d771-3f15-4874-a64c-86a1eba37d81
```

### Technical Analysis

This component will be created in  libs/pages/elewa/venture-labs

The component will be called venture-labs-info

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

### PR DESCRIPTION
**Pull request by Michael-Otieno**
# Description

Worked alone.

This pull request solves issue #402, whereby I have created a venture labs info section following the design's guidelines.

Fixes #402

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
img103
img102

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by IanOdhiambo9 — APPROVED** [review]

**Comment by IanOdhiambo9** [comment]
Please resolve conflict

**Comment by IanOdhiambo9** [comment]
Please resolve conflict

**Comment by Michael-Otieno** [comment]
> Please resolve conflict

Almost done

**Comment by Michael-Otieno** [comment]
Done Please review

**Pull request merged**
