### PR TITLE
#13 feature-home-page-jobs-section

### PR DESCRIPTION
**Pull request by Calvin-Ngugi**
# Description

This pull request is a feature creation of the jobs home-page section which redirects to the upcoming jobs page.

To achieve this, we needed to:

```
- Add a router link to the section
- Make it visible on the page so users can notice it easily
```

Fixes # ([13](https://github.com/italanta/elewa-group/issues/13))

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Screenshot
screenshot_from_2023-02-07_11-43-50

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by IanOdhiambo9 — CHANGES_REQUESTED** [review]
This feature did not require you to create a new package for the job-section. This section is part of the home module.

Your assignment was to create and add the job-section component to the home-page.

Sync your fork and check the folder structure on the home module

**Comment by Calvin-Ngugi** [comment]
I have made corrections and made it a component

**Comment by IanOdhiambo9** [comment]
The module for jobs section still exists

**Comment by IanOdhiambo9** [comment]
I'm closing this pull request because this are too many files to track for this issue

**Pull request closed without merging**
