### PR TITLE
32/social impact cooperative section

### PR DESCRIPTION
**Pull request by NewtonOmbese**
# Description

Created a section that describes the Social Impact cooperative section that shows an image on the right side, a paragraph of text and a title. This component displays provided text and images side by side on the social impact section using the reusable animated button components in issue https://github.com/italanta/elewa-group/issues/31. 

To achieve this, I needed to:
- Step 1: Create the Social Impact cooperative section component
```
nx g @nrwl/angular:component pages/elewa/social-impact
```
- Make an import of the button module to be reused in the component

Fixes # (issue  https://github.com/italanta/elewa-group/issues/32) 

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
Desktop View
social-desktop

Mobile View
social-mobile

# How Has This Been Tested?
Step 1: Added the component to social-impact-page.component.html
Step 2: Started the server by running ```nx serve elewa-group-website```
Step 3: Using chrome developer tools to test on the responsiveness of the website

# Checklist:t
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by NewtonOmbese** [comment]
Review and merge @IanOdhiambo9

**Comment by NewtonOmbese** [comment]
@LemmyMwaura I fixed it earlier before you review it kindly give any more feedback

**Review by LemmyMwaura — COMMENTED** [review]
Fix Order of Imports and pass all the required values

**Comment by LemmyMwaura** [comment]
> @LemmyMwaura review and give feedback

The banners Module should be imported before the components, please fix that.

**Comment by NewtonOmbese** [comment]
@LemmyMwaura  done fixing the needed fixes review kindly

**Comment by IanOdhiambo9** [comment]
Still has unresolved conflicts. You need to merge main to your branch and resolve.

**Review by IanOdhiambo9 — APPROVED** [review]

**Comment by IanOdhiambo9** [comment]
What is your name on slack?

**Comment by NewtonOmbese** [comment]
@IanOdhiambo9  my name is @NewtonOmbese

**Comment by NewtonOmbese** [comment]
Newton Ombese

**Pull request merged**
