### PR TITLE
Issue22/ft history carousel

### PR DESCRIPTION
**Pull request by Beulah-Matt**
# Description
A carousel that can display a history timeline of the organisation

To achieve this, we needed to:

Reuse the component in -timeline carousel (reuse watchhttps://github.com/italanta/elewa-group/issues/21 )
Add a title
Have a call to action section

Fixes # (issue) - https://github.com/italanta/elewa-group/issues/22

## Type of change
This is a feature change 

# Screenshot (optional)

history

calltoaction

# How Has This Been Tested?

Checked for pixel accuracy in my browser and made sure no errors are arising

# Checklist:
- [ ✔️] My code follows the style guidelines of this project
- [✔️ ] I have performed a self-review of my code
- [✔️ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [✔️ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [✔️ ] New and existing unit tests pass locally with my changes
- [ ✔️] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Beulah-Matt** [comment]
@IanOdhiambo9 please review this https://github.com/italanta/elewa-group/pull/237

**Comment by LemmyMwaura** [comment]
This issue was closed #170

**Review by IanOdhiambo9 — COMMENTED** [review]
Good Job on this one, however, there seemed to be two carousel navigation buttons on your screenshot.

**Comment by IanOdhiambo9** [comment]
I'm closing this PR because this issue has been completed

**Pull request closed without merging**
