### PR TITLE
#13 feature-job-section

### PR DESCRIPTION
**Pull request by EliusCaleb**
The task to design :
A feature that is a stand-alone component. This page should be different from the element.
The text "open opportunities" is an anchor link that points to the /jobs page
To achieve this, we needed to:
    1) We need to create a standalone component  that is called job-section
    2) Add view to the components  which is HTML code
    3)Add style to the component
    4) Render this component to the app component
## Type of change
Delete my package.lock json
# Screenshot (optional)
image
# How Has This Been Tested?
When I click the open or opportunities it redirects to /jobs
# Checklist:
- [ 1] My code follows the style guidelines of this project
- [2 ] I have performed a self-review of my code
- [3 ] I have made corresponding changes to the documentation
- [4] Any dependent changes have been merged and published in downstream modules

Screenshot 
image

### CODE REVIEW

**Comment by EliusCaleb** [comment]
Can I have feedback on this

**Review by IanOdhiambo9 — CHANGES_REQUESTED** [review]
Please write a proper description of what you were working on. Provide screenshots as well and tag the issue.

You've also pushed the package-lock.json file. This cannot be merged.
Do a new PR without this file

**Comment by EliusCaleb** [comment]
on it

**Comment by EliusCaleb** [comment]
I changed the files home-job-section is a standalone components

**Pull request closed without merging**
